export const PURPOSE_CODES_LIST = [
  {
    CountryCode: 'AE',
    PurposeCode: 'ACM',
    ClearingType: 8,
    PurposeCodeDescription: 'Agency Commission',
    PurposeCodeClassification: 'Beneficiary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0001',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'AES',
    ClearingType: 8,
    PurposeCodeDescription: 'Advance Payment against',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'AFA',
    ClearingType: 8,
    PurposeCodeDescription: 'Receipts or payments from personal residents bank account or deposits abroad',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'AFL',
    ClearingType: 8,
    PurposeCodeDescription: 'Receipts or payments from personal n-resident bank account in the UAE',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'ALW',
    ClearingType: 8,
    PurposeCodeDescription: 'Allowance',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'ATS',
    ClearingType: 8,
    PurposeCodeDescription: 'Air transport',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'BON',
    ClearingType: 8,
    PurposeCodeDescription: 'Bonus',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CBP',
    ClearingType: 8,
    PurposeCodeDescription: 'Cross Border Payments',
    PurposeCodeClassification: 'General',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0021',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CCP',
    ClearingType: 8,
    PurposeCodeDescription: 'Customer Card Payment',
    PurposeCodeClassification: 'Beneficiary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0001',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CEA',
    ClearingType: 8,
    PurposeCodeDescription:
      'Equity for the establishment of new company from residents abroad equity of merger or acquisition of companies abroad from residents and participation to capital increase of related company abroad',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CEL',
    ClearingType: 8,
    PurposeCodeDescription:
      'Equity for the establishment of new company in the UAE from residents equity of merger or acquisition of companies in the UAE from n-residents participation to capital increase of related companies',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CHC',
    ClearingType: 8,
    PurposeCodeDescription: 'Charitable Contributions',
    PurposeCodeClassification: 'Beneficiary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0001',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CIN',
    ClearingType: 8,
    PurposeCodeDescription: 'Commercial Investments',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'COM',
    ClearingType: 8,
    PurposeCodeDescription: 'Commission',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'COP',
    ClearingType: 8,
    PurposeCodeDescription: 'Compensation',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'CRP',
    ClearingType: 8,
    PurposeCodeDescription: 'Credit Card Payment',
    PurposeCodeClassification: 'Beneficiary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0001',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'DCP',
    ClearingType: 8,
    PurposeCodeDescription: 'Pre-Paid Reloadable & Personalized Debit Card Payments',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'DIF',
    ClearingType: 8,
    PurposeCodeDescription: 'Debt instruments intragroup loans securities deposits foreign',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'DIL',
    ClearingType: 8,
    PurposeCodeDescription: 'Debt instruments intragroup loans securities deposits in the UAE',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'DIV',
    ClearingType: 8,
    PurposeCodeDescription: 'Dividend Payouts',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'DLA',
    ClearingType: 8,
    PurposeCodeDescription: 'Purchases and sales of foreign debt securities more than a year in t related companies',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
  {
    CountryCode: 'AE',
    PurposeCode: 'DLL',
    ClearingType: 8,
    PurposeCodeDescription: 'Purchases and sales of securities issued by residents more than a year in t related companies',
    PurposeCodeClassification: 'Beneficiary, Salary and Remittance',
    MessageType: 103,
    Direction: 2,
    TransactionType: 'ALL',
    MainCategoryCode: '0002',
    SubCategoryCode: '0003',
  },
];
